### ISSUE TITLE
Why GitLab is not in the Rails section?

### ISSUE THREAD

**Issue by dalerka** [unicodeveloper/awesome-opensource-webapps#3]
[GitLab](https://about.gitlab.com/community/) is similar to Github, and in some sense to Redmine, IMHO. Are there specific things that make GitLab less "awesome" then other software listed in Rails section?

**Comment by unicodeveloper** [comment]
It didn't come to mind when I was curating. Do you wanna submit a PR to include that @dalerka ? I'll surely accept a good PR.

**Comment by unicodeveloper** [comment]
I'll close this now because there is no PR for it. Please feel free to reopen it whenever you want to send a PR @dalerka
